version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "jooy2"
    reviewers:
      - "jooy2"
    open-pull-requests-limit: 30
    versioning-strategy: increase
