name: 'Fix typo request'
description: Request to fix a typo or bad translation in this project
labels: ['typo']
body:
  - type: markdown
    attributes:
      value: |
        Before creating an issue, please read the following:

        - Search to see if the same issue already exists, and keep the title concise and accurate so that it's easy for others to understand and search for.
        - Please create a separate issue for each type of issue.
        - Please be as detailed as possible and write in English so that we can handle your issue quickly.
  - type: textarea
    attributes:
      label: Describe the issue
      description: Please describe where the typo occurs and a list of text that needs to be corrected.
    validations:
      required: true
